#!/usr/bin/env python
"""Build the UNLABELLED BPM/key annotation manifest from the CC corpus.

This writes the schema and the track selection. It deliberately does **not**
write BPM or key values: those require a human listening to the audio, and
inventing them would produce a benchmark that measures nothing while looking
authoritative. Every row starts `annotation_status: "pending"` with null labels.

Selection is deterministic -- a fixed stride over track_id-sorted corpus entries
-- so re-running reproduces the same set. Only tracks whose recorded licence is
permissive are eligible, using the same rule the corpus fetcher applied.

    python scripts/build_bpm_key_manifest.py --count 60 --dry-run
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))

import hashlib                                                        # noqa: E402

SCHEMA_VERSION = 1
DEFAULT_SOURCE = "eval/fixtures/scale_corpus_manifest.json"
DEFAULT_OUT = "eval/fixtures/bpm_key_annotation_manifest.json"

# The corpus fetcher's rule, restated: anything non-commercial or no-derivatives
# is excluded, so the fixture set stays redistributable under the project's
# established licensing posture.
FORBIDDEN_LICENSE_TOKENS = ("-nd", "-nc", "/nc-", "by-nc", "by-nd", "nc-sa", "nc-nd")


def licence_is_permissive(url: str | None, name: str | None) -> bool:
    blob = f"{url or ''} {name or ''}".lower()
    if not blob.strip():
        return False
    return not any(tok in blob for tok in FORBIDDEN_LICENSE_TOKENS)


def select(tracks: list[dict], count: int) -> list[dict]:
    """A deterministic, evenly-spread selection of permissively licensed tracks."""
    eligible = sorted(
        (t for t in tracks
         if licence_is_permissive(t.get("license_url"), t.get("license"))),
        key=lambda t: t["track_id"])
    if not eligible:
        return []
    if count >= len(eligible):
        return eligible
    stride = len(eligible) / count
    return [eligible[int(i * stride)] for i in range(count)]


def build_rows(chosen: list[dict]) -> list[dict]:
    return [{
        "track_id": t["track_id"],
        "path": t["path"],
        "sha256": t["sha256"],
        "title": t.get("title"),
        "artist": t.get("artist"),
        "duration_sec": float(t["duration_sec"]),
        "license": t.get("license"),
        "license_url": t.get("license_url"),
        "source": t.get("source"),
        "source_url": t.get("source_url"),

        # ---- ground truth: to be filled by a human, never by a program ----
        # bpm: a number, or the string "no_stable_tempo".
        "bpm": None,
        # key: a 24-class name such as "C major" / "F# minor", or
        # "no_tonal_centre". Normalised via musicintel.analysis.keys.parse_key.
        "key": None,
        # pending | annotated | excluded
        "annotation_status": "pending",
        "annotator": None,
        "annotated_utc": None,
        "notes": "",
    } for t in chosen]


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--source", type=Path, default=REPO_ROOT / DEFAULT_SOURCE)
    ap.add_argument("--out", type=Path, default=REPO_ROOT / DEFAULT_OUT)
    ap.add_argument("--count", type=int, default=60,
                    help="target track count (roadmap guidance: 50-100)")
    ap.add_argument("--dry-run", action="store_true")
    args = ap.parse_args(argv)

    source = json.loads(Path(args.source).read_text())
    tracks = source.get("tracks", [])
    chosen = select(tracks, args.count)

    missing = [t["track_id"] for t in chosen
               if not (REPO_ROOT / t["path"]).exists()]

    # Identity of WHICH tracks the fixture set holds, over (track_id, sha256)
    # pairs only -- the same rule Catalog.content_hash() uses. Deliberately not
    # a git fingerprint: a manifest that embeds volatile repository state cannot
    # be regenerated byte-identically, and the frozen corpus manifests carry a
    # content hash for exactly this reason.
    content_hash = hashlib.sha256(json.dumps(
        sorted((t["track_id"], t["sha256"]) for t in chosen),
        sort_keys=True).encode()).hexdigest()

    payload = {
        "schema_version": SCHEMA_VERSION,
        "content_hash": content_hash,
        "fixture_set": "bpm_key_v1",
        "purpose": ("Project-owned BPM/key ground truth for Stage 4 evaluation. "
                    "Labels are supplied by a human annotator; this file is "
                    "generated UNLABELLED and must never be auto-filled."),
        "annotation_protocol": "docs/analysis-evaluation.md",
        "source_manifest": str(Path(args.source).relative_to(REPO_ROOT)),
        "source_manifest_content_hash": source.get("content_hash"),
        "license_policy": ("permissive CC only; non-commercial and "
                           "no-derivatives licences are excluded"),
        "license_counts": _counts(chosen, "license"),
        "track_count": len(chosen),
        "annotated_count": 0,
        "tracks": build_rows(chosen),
    }

    print(f"  source          : {args.source}")
    print(f"  eligible tracks : {len(tracks)} in source")
    print(f"  selected        : {len(chosen)} (deterministic stride)")
    print(f"  licences        : {payload['license_counts']}")
    print(f"  audio present   : {len(chosen) - len(missing)}/{len(chosen)}")
    if missing:
        print(f"  MISSING AUDIO   : {missing[:5]}")
    print(f"  content_hash    : {content_hash}")
    print(f"  labels written  : 0  (all rows annotation_status='pending')")

    if args.dry_run:
        print("\n  dry run: nothing written")
        return 0
    Path(args.out).write_text(json.dumps(payload, indent=2, sort_keys=True) + "\n")
    print(f"\n  written: {args.out}")
    return 0


def _counts(rows: list[dict], field: str) -> dict:
    out: dict[str, int] = {}
    for r in rows:
        out[str(r.get(field))] = out.get(str(r.get(field)), 0) + 1
    return dict(sorted(out.items()))


if __name__ == "__main__":
    raise SystemExit(main())
